### ISSUE TITLE
如何关闭路由缓存

### ISSUE THREAD

**Issue by hqs-concha** [yalin28/vue-antdesign-admin-template#3]
比如list列表中点击详情进如到detail?id=1页面，再在list列表中点击详情进如到detail?id=2页面会显示id=1的详情，除非关了顶部tab栏

**Comment by yalin28** [comment]
通过你的描述，我感觉可以尝试把 `src/layouts/RouteLayout.vue` 中的 `router-view`  `key` 属性计算方式从 `$route.path` 换成 `$route.fullPath` 。

**Comment by hqs-concha** [comment]
谢谢，将 `$route.path` 改为 `$route.fullPath` 完美解决。设置 `keepalive` 的值没有作用
