### ISSUE TITLE
请问一下有些组件（antd的组件）没有该如何注册呢

### ISSUE THREAD

**Issue by hqs-concha** [yalin28/vue-antdesign-admin-template#4]
比如：`a-cascader`  级联组件，`a-form-model` 表单组件，使用的时候会报错
`Unknown custom element: <a-cascader> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by yalin28** [comment]
在 `/src/core/lazy_lib/components_use.js` 目录中进行引入组件。

具体组件注册方式查看官方文档 

例如：`FormModel` 「参考： https://antdv.com/components/form-model-cn/ 」

**Comment by hqs-concha** [comment]
谢谢大佬
