### ISSUE TITLE
切换顶部导航栏的时候，页面异常

### ISSUE THREAD

**Issue by gynsxk** [yalin28/vue-antdesign-admin-template#6]
![image](https://user-images.githubusercontent.com/47736620/108811135-a7520e80-75e7-11eb-948d-2c1629eaad44.png)

标签飘到右上角了

**Comment by yalin28** [comment]
问题已复现，跟进中。

**Comment by yalin28** [comment]
> ![image](https://user-images.githubusercontent.com/47736620/108811135-a7520e80-75e7-11eb-948d-2c1629eaad44.png)
> 
> 标签飘到右上角了

已修复。

**Comment by gynsxk** [comment]
确实解决了飘的问题，但是页标签页不存在了，在开启多标签的情况下，多了一段空白。

**Comment by yalin28** [comment]
> 确实解决了飘的问题，但是页标签页不存在了，在开启多标签的情况下，多了一段空白。

**Comment by yalin28** [comment]
> 确实解决了飘的问题，但是页标签页不存在了，在开启多标签的情况下，多了一段空白。

感谢反馈。看了下，当初设计这里是有点不合理，顶部导航的时候不应该提供开启多标签的功能，后面将会处理为开启顶部导航的时候禁用掉「多标签模式」的开关操作。类似顶部导航模式禁用固定侧边栏。

**Comment by yalin28** [comment]
> 确实解决了飘的问题，但是页标签页不存在了，在开启多标签的情况下，多了一段空白。

已经修复。
